#!/bin/bash -e
if [[ ! -f "/home/spark-b7803a06-a3ff-4f79-8e9f-97/tmp/uv/uv_0.6.10_linux_arm64" ]]; then
  curl -LsSf https://astral.sh/uv/0.6.10/install.sh | sh
  exec "$HOME/.local/bin/uv" "$@"
fi
exec "/home/spark-b7803a06-a3ff-4f79-8e9f-97/tmp/uv/uv_0.6.10_linux_arm64" "$@"
